version: '3'

services:
  web:
    build:
      context: .
      args:
        - dir=${DIRECTORY}
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www
      - ${DIRECTORY}:${DIRECTORY}
    ports:
      - "8000:8000"
    env_file:
      - .env

